"""

Revision ID: 1614ac238b64
Revises: c616424fda8c
Create Date: 2025-05-06 09:06:11.062861

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '1614ac238b64'
down_revision: str | None = 'c616424fda8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
