"""모델 관계 및 MailLog user_id 타입 수정

Revision ID: 1b29ea7e0238
Revises: 2d3266daefe8
Create Date: 2025-04-27 15:57:50.512555

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b29ea7e0238'
down_revision: str | None = '2d3266daefe8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail_logs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('mail_logs', sa.Column('keyword_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'mail_logs', 'hotdeal_keywords', ['keyword_id'], ['id'])
    op.create_foreign_key(None, 'mail_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mail_logs', type_='foreignkey')
    op.drop_constraint(None, 'mail_logs', type_='foreignkey')
    op.drop_column('mail_logs', 'keyword_id')
    op.drop_column('mail_logs', 'user_id')
    # ### end Alembic commands ###
