"""Add WorkerLog

Revision ID: 2cc22413adda
Revises: 1e30490edb12
Create Date: 2026-01-27 04:16:50.697818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc22413adda'
down_revision: Union[str, None] = '1e30490edb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAIL', 'RUNNING', name='workerstatus'), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('hotdeal_keyword_sites_keyword_id_fkey'), 'hotdeal_keyword_sites', type_='foreignkey')
    op.create_foreign_key(None, 'hotdeal_keyword_sites', 'hotdeal_keywords', ['keyword_id'], ['id'])
    op.drop_constraint(op.f('user_keywords_keyword_id_fkey'), 'user_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'user_keywords', 'hotdeal_keywords', ['keyword_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_keywords', type_='foreignkey')
    op.create_foreign_key(op.f('user_keywords_keyword_id_fkey'), 'user_keywords', 'hotdeal_keywords', ['keyword_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'hotdeal_keyword_sites', type_='foreignkey')
    op.create_foreign_key(op.f('hotdeal_keyword_sites_keyword_id_fkey'), 'hotdeal_keyword_sites', 'hotdeal_keywords', ['keyword_id'], ['id'], ondelete='CASCADE')
    op.drop_table('worker_logs')
    # ### end Alembic commands ###
