"""User, Keyword, MailLog 모델 관계 설정 및 user_keywords 테이블 추가

Revision ID: 2d3266daefe8
Revises: bd2a7674a124
Create Date: 2025-04-27 15:53:34.087944

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d3266daefe8'
down_revision: str | None = 'bd2a7674a124'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotdeal_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('wdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', name='uq_keywords_title')
    )
    op.create_table('mail_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_keywords',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['hotdeal_keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_keywords')
    op.drop_table('mail_logs')
    op.drop_table('hotdeal_keywords')
    # ### end Alembic commands ###
