"""

Revision ID: 874f88d33a9f
Revises: 1b29ea7e0238
Create Date: 2025-04-28 13:29:27.428308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874f88d33a9f'
down_revision: Union[str, None] = '1b29ea7e0238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotdeal_keyword_sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.Enum('ALGUMON', 'FMKOREA', name='sitename'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('wdate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['hotdeal_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hotdeal_keywords', 'external_id')
    op.drop_column('hotdeal_keywords', 'meta_data')
    op.drop_column('hotdeal_keywords', 'link')
    op.drop_column('hotdeal_keywords', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotdeal_keywords', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotdeal_keywords', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotdeal_keywords', sa.Column('meta_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hotdeal_keywords', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('hotdeal_keyword_sites')
    # ### end Alembic commands ###
