"""hotdeal_keyword_sites 테이블에 ON DELETE CASCADE 추가

Revision ID: 8a91ecfb95a9
Revises: 1614ac238b64
Create Date: 2025-05-07 23:38:31.120905

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a91ecfb95a9"
down_revision: str | None = "1614ac238b64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "hotdeal_keyword_sites_keyword_id_fkey",
        "hotdeal_keyword_sites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "hotdeal_keyword_sites_keyword_id_fkey",  # 제약 조건 이름
        "hotdeal_keyword_sites",  # 소스 테이블
        "hotdeal_keywords",  # 대상 테이블
        ["keyword_id"],  # 소스 테이블의 컬럼
        ["id"],  # 대상 테이블의 컬럼
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "hotdeal_keyword_sites_keyword_id_fkey",
        "hotdeal_keyword_sites",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "hotdeal_keyword_sites_keyword_id_fkey",  # 제약 조건 이름
        "hotdeal_keyword_sites",  # 소스 테이블
        "hotdeal_keywords",  # 대상 테이블
        ["keyword_id"],  # 소스 테이블의 컬럼
        ["id"],  # 대상 테이블의 컬럼
    )
    # ### end Alembic commands ###
