"""

Revision ID: c616424fda8c
Revises: e2fe0b442080
Create Date: 2025-05-06 08:50:59.542938

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c616424fda8c"
down_revision: str | None = "e2fe0b442080"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_keyword_site', 'hotdeal_keyword_sites', ['keyword_id', 'site_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_keyword_site', 'hotdeal_keyword_sites', type_='unique')
    # ### end Alembic commands ###
