"""첫 마이그레이션: users 테이블 생성

Revision ID: c9fbbb98ef9a
Revises:
Create Date: 2025-04-22 00:01:39.080019

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c9fbbb98ef9a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
